"""Mirror of lib/init.js — embeds core skill + resolver block into IDE rules files."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from rich.console import Console

from .checksum import compute_file_checksum
from .fetch import get_core
from .keywords import TRIGGERS_PATH, load_triggers

console = Console(highlight=False)

HEADER = (
    "# Aigis core skill — installed by `aigis init`\n"
    "# Re-run `aigis init <ide>` to refresh this file when Aigis updates.\n"
    "# Area + workflow skills load on demand via the aigis CLI; they are NOT in this file.\n\n"
)

RESOLVER_BLOCK_RE = re.compile(
    r"# --- AIGIS RESOLVER BLOCK START \(checksum: ([a-f0-9]+)\) ---[\s\S]*?# --- AIGIS RESOLVER BLOCK END ---",
    re.MULTILINE,
)


IDE_DESTINATIONS: dict[str, dict] = {
    "cursor":      {"file": ".cursorrules",                  "instruction": "Cursor will read these instructions on every interaction in this project."},
    "windsurf":    {"file": ".windsurfrules",                "instruction": "Windsurf will read these instructions on every interaction in this project."},
    "copilot":     {"file": ".github/copilot-instructions.md", "instruction": "Copilot will read these instructions for this repository."},
    "claude-code": {"file": None,                            "instruction": "Claude Code will read this skill file. Restart Claude Code for it to take effect."},
}


def _short_question(prompt: str) -> str:
    m = re.match(r"^You mentioned [^.]+\.\s*(.+?)\s*\(yes / no / unsure\)\s*$", prompt)
    return m.group(1) if m else prompt


def render_resolver_block(checksum: str) -> str:
    triggers = load_triggers()
    lines: list[str] = []
    lines.append(f"# --- AIGIS RESOLVER BLOCK START (checksum: {checksum}) ---")
    lines.append(f"# Generated by `aigis init` from content/resolvers/triggers.json (version {triggers['version']}).")
    lines.append("# Do not edit manually. Run `aigis init <ide> --refresh` to regenerate after Aigis updates.")
    lines.append("#")
    lines.append("# When the user describes their project in natural language, scan the description")
    lines.append("# for the phrases below.")
    lines.append("#")
    lines.append("# HIGH-CONFIDENCE: apply the listed traits directly.")
    lines.append("# LOW-CONFIDENCE:  ask the user the listed clarifying question; apply the trait")
    lines.append("#                  only if they confirm \"yes\". Default to \"no\" if the user is")
    lines.append("#                  unsure. Record \"unsure\" answers distinctly from \"no\" so future")
    lines.append("#                  iterations can ask again.")
    lines.append("")
    lines.append("## High-confidence triggers (auto-apply)")
    lines.append("")

    hi = triggers["high_confidence"]
    hi_keys = list(hi.keys())
    pw = max(6, *(len(k) for k in hi_keys))
    tw = max(6, *(len(", ".join(hi[k]["traits"])) for k in hi_keys))
    lines.append(f"| {'Phrase'.ljust(pw)} | {'Traits'.ljust(tw)} |")
    lines.append(f"|{'-' * (pw + 2)}|{'-' * (tw + 2)}|")
    for k in hi_keys:
        lines.append(f"| {k.ljust(pw)} | {', '.join(hi[k]['traits']).ljust(tw)} |")

    lines.append("")
    lines.append("## Low-confidence triggers (confirm with user before applying)")
    lines.append("")

    lo = triggers["low_confidence"]
    lo_keys = list(lo.keys())
    lpw = max(6, *(len(k) for k in lo_keys))
    ltw = max(6, *(len(", ".join(lo[k]["traits"])) for k in lo_keys))
    askw = max(6, *(len(_short_question(lo[k]["confirmation_prompt"])) for k in lo_keys))
    lines.append(f"| {'Phrase'.ljust(lpw)} | {'Traits'.ljust(ltw)} | {'Ask the user'.ljust(askw)} |")
    lines.append(f"|{'-' * (lpw + 2)}|{'-' * (ltw + 2)}|{'-' * (askw + 2)}|")
    for k in lo_keys:
        e = lo[k]
        lines.append(f"| {k.ljust(lpw)} | {', '.join(e['traits']).ljust(ltw)} | {_short_question(e['confirmation_prompt']).ljust(askw)} |")

    lines.append("")
    lines.append("# --- AIGIS RESOLVER BLOCK END ---")
    return "\n".join(lines)


def _build_full_content() -> tuple[str, str]:
    checksum = compute_file_checksum(TRIGGERS_PATH)
    block = render_resolver_block(checksum)
    return HEADER + get_core() + "\n\n" + block + "\n", checksum


def _write_or_refresh(target: Path, content: str, expected: str, refresh: bool, instruction: str, ide_name: str, display: str) -> None:
    if not target.exists():
        target.write_text(content, encoding="utf-8")
        console.print(f"\n[green]✓ Created {display}[/green]\n")
        console.print(f"[dim]{instruction}\n[/dim]")
        return

    existing = target.read_text(encoding="utf-8")
    match = RESOLVER_BLOCK_RE.search(existing)
    has_core = "aigis-core" in existing

    if not has_core and not match:
        with target.open("a", encoding="utf-8") as f:
            f.write("\n\n" + content)
        console.print(f"\n[green]✓ Appended aigis core + resolver block to {display}[/green]\n")
        console.print(f"[dim]Your existing rules are preserved.[/dim]")
        console.print(f"[dim]{instruction}\n[/dim]")
        return

    if refresh:
        target.write_text(content, encoding="utf-8")
        console.print(f"\n[green]✓ Refreshed {display} (resolver checksum: {expected[:12]}...)[/green]\n")
        console.print(f"[dim]{instruction}\n[/dim]")
        return

    if match and match.group(1) == expected:
        console.print(f"\n[dim]{display} is up to date (resolver checksum matches).[/dim]\n")
        return

    console.print(f"\n[yellow]⚠ {display} already contains an aigis section.[/yellow]")
    if match:
        console.print(f"[dim]  Existing block checksum: {match.group(1)[:12]}...[/dim]")
        console.print(f"[dim]  Current triggers.json:   {expected[:12]}...[/dim]")
        console.print("[dim]  These differ — your aigis content is out of date or has been edited.[/dim]")
    else:
        console.print("[dim]  No resolver block detected, but core marker present.[/dim]")
    console.print("")
    console.print("Options:")
    console.print(f"  [green]aigis init {ide_name} --refresh[/green]    overwrite the file with the current Aigis core + resolver block")
    console.print(f"  manually remove the existing aigis section, then re-run [green]aigis init {ide_name}[/green]")
    console.print("")
    sys.exit(1)


def init(ide: str, refresh: bool = False) -> None:
    ide_lower = ide.lower()
    dest = IDE_DESTINATIONS.get(ide_lower)
    if not dest:
        console.print(f"[red]Unknown IDE: {ide}[/red]")
        console.print("[dim]Available: cursor, claude-code, windsurf, copilot\n[/dim]")
        sys.exit(1)

    content, checksum = _build_full_content()

    if ide_lower == "claude-code":
        skill_dir = Path.home() / ".claude" / "skills" / "aigis"
        skill_file = skill_dir / "SKILL.md"
        skill_dir.mkdir(parents=True, exist_ok=True)
        _write_or_refresh(skill_file, content, checksum, refresh, dest["instruction"], ide_lower, str(skill_file))
        return

    target = Path.cwd() / dest["file"]
    target.parent.mkdir(parents=True, exist_ok=True)
    _write_or_refresh(target, content, checksum, refresh, dest["instruction"], ide_lower, dest["file"])
