const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const { getCore } = require('./fetch');
const { loadTriggers, TRIGGERS_PATH } = require('./keywords');
const { computeFileChecksum } = require('./checksum');

const HEADER = `# Aigis core skill — installed by \`aigis init\`
# Re-run \`aigis init <ide>\` to refresh this file when Aigis updates.
# Area + workflow skills load on demand via the aigis CLI; they are NOT in this file.

`;

const RESOLVER_BLOCK_START = (checksum) =>
  `# --- AIGIS RESOLVER BLOCK START (checksum: ${checksum}) ---`;
const RESOLVER_BLOCK_END = `# --- AIGIS RESOLVER BLOCK END ---`;
const RESOLVER_BLOCK_RE = /# --- AIGIS RESOLVER BLOCK START \(checksum: ([a-f0-9]+)\) ---[\s\S]*?# --- AIGIS RESOLVER BLOCK END ---/m;

const IDE_DESTINATIONS = {
  cursor:        { file: '.cursorrules',                  description: 'Cursor rules file',          instruction: 'Cursor will read these instructions on every interaction in this project.' },
  windsurf:      { file: '.windsurfrules',                description: 'Windsurf rules file',         instruction: 'Windsurf will read these instructions on every interaction in this project.' },
  copilot:       { file: '.github/copilot-instructions.md', description: 'GitHub Copilot instructions', instruction: 'Copilot will read these instructions for this repository.' },
  'claude-code': { file: null,                            description: 'Claude Code skill file',      instruction: 'Claude Code will read this skill file. Restart Claude Code for it to take effect.' },
};

/**
 * Render the resolver block as a human-readable markdown table the agent can
 * consume directly. Format is deterministic: alphabetical row order within
 * each tier, fixed column widths, no trailing whitespace.
 */
function renderResolverBlock(checksum) {
  const triggers = loadTriggers();

  const lines = [];
  lines.push(RESOLVER_BLOCK_START(checksum));
  lines.push(`# Generated by \`aigis init\` from content/resolvers/triggers.json (version ${triggers.version}).`);
  lines.push(`# Do not edit manually. Run \`aigis init <ide> --refresh\` to regenerate after Aigis updates.`);
  lines.push(`#`);
  lines.push(`# When the user describes their project in natural language, scan the description`);
  lines.push(`# for the phrases below.`);
  lines.push(`#`);
  lines.push(`# HIGH-CONFIDENCE: apply the listed traits directly.`);
  lines.push(`# LOW-CONFIDENCE:  ask the user the listed clarifying question; apply the trait`);
  lines.push(`#                  only if they confirm "yes". Default to "no" if the user is`);
  lines.push(`#                  unsure. Record "unsure" answers distinctly from "no" so future`);
  lines.push(`#                  iterations can ask again.`);
  lines.push('');
  lines.push('## High-confidence triggers (auto-apply)');
  lines.push('');

  const hiKeys = Object.keys(triggers.high_confidence);
  const phraseW = Math.max(6, ...hiKeys.map((k) => k.length));
  const traitsW = Math.max(6, ...hiKeys.map((k) => triggers.high_confidence[k].traits.join(', ').length));
  lines.push(`| ${'Phrase'.padEnd(phraseW)} | ${'Traits'.padEnd(traitsW)} |`);
  lines.push(`|${'-'.repeat(phraseW + 2)}|${'-'.repeat(traitsW + 2)}|`);
  for (const k of hiKeys) {
    lines.push(`| ${k.padEnd(phraseW)} | ${triggers.high_confidence[k].traits.join(', ').padEnd(traitsW)} |`);
  }

  lines.push('');
  lines.push('## Low-confidence triggers (confirm with user before applying)');
  lines.push('');

  const loKeys = Object.keys(triggers.low_confidence);
  const lpW = Math.max(6, ...loKeys.map((k) => k.length));
  const ltW = Math.max(6, ...loKeys.map((k) => triggers.low_confidence[k].traits.join(', ').length));
  // Question column kept compact — the full prompt is long; we render the trailing
  // question only (sentence between "You mentioned X." and the "(yes / no / unsure)" suffix).
  function shortQuestion(prompt) {
    const m = prompt.match(/^You mentioned [^.]+\.\s*(.+?)\s*\(yes \/ no \/ unsure\)\s*$/);
    return m ? m[1] : prompt;
  }
  const askW = Math.max(6, ...loKeys.map((k) => shortQuestion(triggers.low_confidence[k].confirmation_prompt).length));
  lines.push(`| ${'Phrase'.padEnd(lpW)} | ${'Traits'.padEnd(ltW)} | ${'Ask the user'.padEnd(askW)} |`);
  lines.push(`|${'-'.repeat(lpW + 2)}|${'-'.repeat(ltW + 2)}|${'-'.repeat(askW + 2)}|`);
  for (const k of loKeys) {
    const e = triggers.low_confidence[k];
    lines.push(`| ${k.padEnd(lpW)} | ${e.traits.join(', ').padEnd(ltW)} | ${shortQuestion(e.confirmation_prompt).padEnd(askW)} |`);
  }

  lines.push('');
  lines.push(RESOLVER_BLOCK_END);
  return lines.join('\n');
}

function buildFullContent() {
  const checksum = computeFileChecksum(TRIGGERS_PATH);
  const block = renderResolverBlock(checksum);
  return { content: HEADER + getCore() + '\n\n' + block + '\n', checksum };
}

function init(ide, opts = {}) {
  const ideLower = ide.toLowerCase();
  const dest = IDE_DESTINATIONS[ideLower];
  if (!dest) {
    console.error(chalk.red(`Unknown IDE: ${ide}`));
    console.log(chalk.dim('Available: cursor, claude-code, windsurf, copilot\n'));
    process.exit(1);
  }

  const { content, checksum } = buildFullContent();

  // Claude Code: dedicated skill dir
  if (ideLower === 'claude-code') {
    const skillDir = path.join(require('os').homedir(), '.claude', 'skills', 'aigis');
    const skillFile = path.join(skillDir, 'SKILL.md');
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    writeOrRefresh(skillFile, content, checksum, opts.refresh, dest.instruction, ideLower);
  } else {
    // Other IDEs
    const targetFile = path.resolve(dest.file);
    const targetDir = path.dirname(targetFile);
    if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
    writeOrRefresh(targetFile, content, checksum, opts.refresh, dest.instruction, ideLower, dest.file);
  }

  // v2.1: optional activation surfaces — additive, opt-in via flags.
  if (opts.ci === 'github' || opts.ci === true) {
    installGithubAction({ refresh: !!opts.refresh });
  }
  if (opts.hook) {
    installPreCommitHook({ refresh: !!opts.refresh });
  }
}

/**
 * v2.1 — GitHub Action template installer.
 *
 * Drops `.github/workflows/aigis.yml` into the repo. The workflow runs
 * `aigis report --areas <list> --project .` on every pull_request, where
 * the area list comes from an opt-in `.aigisrc.json` file the user maintains.
 * No `.aigisrc.json` → workflow no-ops with a helpful message.
 *
 * Refresh model identical to the IDE rules block: checksum-guarded; existing
 * file with matching checksum is left alone; mismatch errors with --refresh hint.
 */
function installGithubAction({ refresh = false } = {}) {
  const targetDir = path.resolve('.github', 'workflows');
  const targetFile = path.join(targetDir, 'aigis.yml');
  const display = '.github/workflows/aigis.yml';
  const content = renderGithubActionWorkflow();
  // Checksum is over the BODY only (not the comment header that contains the
  // checksum itself — would be self-referential). Must match what
  // renderGithubActionWorkflow embeds in the header tag.
  const checksum = sha256(GITHUB_ACTION_BODY).slice(0, 12);

  if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

  if (!fs.existsSync(targetFile)) {
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`✓ Installed CI workflow: ${display}`));
    console.log(chalk.dim('  Add a .aigisrc.json to your repo root to declare which areas to verify on PRs.'));
    console.log(chalk.dim('  Example: { "areas": ["pii-handling", "audit-logging"], "jurisdiction": "eu" }\n'));
    return;
  }

  // Existing file — check checksum
  const existing = fs.readFileSync(targetFile, 'utf8');
  const existingChecksum = (existing.match(/# aigis-action-checksum: ([a-f0-9]+)/) || [])[1];
  if (existingChecksum === checksum) {
    console.log(chalk.dim(`${display} is up to date.`));
    return;
  }
  if (refresh) {
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`✓ Refreshed ${display} (checksum: ${checksum})`));
    return;
  }
  console.log(chalk.yellow(`⚠ ${display} exists with a different checksum.`));
  console.log(chalk.dim(`  Existing: ${existingChecksum || '(no checksum tag)'}`));
  console.log(chalk.dim(`  Current:  ${checksum}`));
  console.log(`  Re-run with ${chalk.green('--refresh')} to overwrite, or remove the file manually.`);
}

function renderGithubActionWorkflow() {
  // Single, opinionated workflow. Reads .aigisrc.json from the repo root for
  // configuration. No magic — the user opts in by creating that file.
  const checksum = sha256(GITHUB_ACTION_BODY).slice(0, 12);
  return `# aigis-action-checksum: ${checksum}
# Installed by \`aigis init <ide> --ci github\`. Re-run with --refresh to update.
# Configure areas to verify by creating a .aigisrc.json in your repo root:
#   { "areas": ["pii-handling", "audit-logging"], "jurisdiction": "eu" }
${GITHUB_ACTION_BODY}`;
}

const GITHUB_ACTION_BODY = `name: aigis governance

on:
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  verify:
    name: aigis verify (declared areas)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install aigis
        run: npm install -g @aigis-ai/cli

      - name: Read .aigisrc.json
        id: config
        run: |
          if [ -f .aigisrc.json ]; then
            AREAS=$(node -e "console.log((JSON.parse(require('fs').readFileSync('.aigisrc.json'))['areas']||[]).join(','))")
            JUR=$(node -e "console.log(JSON.parse(require('fs').readFileSync('.aigisrc.json'))['jurisdiction']||'')")
            echo "areas=$AREAS" >> "$GITHUB_OUTPUT"
            echo "jurisdiction=$JUR" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::No .aigisrc.json found. Aigis is installed but no areas declared. See https://github.com/NayanKanaparthi/aigis"
            echo "areas=" >> "$GITHUB_OUTPUT"
            echo "jurisdiction=" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate compliance report
        if: steps.config.outputs.areas != ''
        run: |
          ARGS="--areas \${{ steps.config.outputs.areas }} --project ."
          if [ -n "\${{ steps.config.outputs.jurisdiction }}" ]; then
            ARGS="$ARGS --jurisdiction \${{ steps.config.outputs.jurisdiction }}"
          fi
          aigis report $ARGS --output aigis-report.md
          cat aigis-report.md

      - name: Upload report artifact
        if: steps.config.outputs.areas != ''
        uses: actions/upload-artifact@v4
        with:
          name: aigis-compliance-report
          path: aigis-report.md
          retention-days: 30

      - name: Run verify (per area, exit on FAIL)
        if: steps.config.outputs.areas != ''
        run: |
          IFS=',' read -ra AREA_LIST <<< "\${{ steps.config.outputs.areas }}"
          FAILED=0
          for AREA in "\${AREA_LIST[@]}"; do
            AREA=$(echo "$AREA" | xargs)
            JUR_FLAG=""
            if [ -n "\${{ steps.config.outputs.jurisdiction }}" ]; then
              JUR_FLAG="--jurisdiction \${{ steps.config.outputs.jurisdiction }}"
            fi
            if ! aigis verify "$AREA" --auto . $JUR_FLAG > /tmp/aigis-$AREA.txt; then
              echo "::error title=aigis verify $AREA::FAIL or OVERCLAIM detected"
              cat /tmp/aigis-$AREA.txt
              FAILED=1
            else
              echo "::group::aigis verify $AREA"
              cat /tmp/aigis-$AREA.txt
              echo "::endgroup::"
            fi
          done
          if [ "$FAILED" -ne 0 ]; then exit 1; fi
`;

/**
 * v2.1 — Pre-commit hook installer.
 *
 * Drops `.git/hooks/pre-commit` shell script. Runs `aigis verify` on
 * areas declared in `.aigisrc.json`. Blocks commit on FAIL/OVERCLAIM.
 * No `.aigisrc.json` → no-op (lets commit through with a notice).
 *
 * Refresh-guarded with checksum tag in the script header.
 */
function installPreCommitHook({ refresh = false } = {}) {
  const targetDir = path.resolve('.git', 'hooks');
  const targetFile = path.join(targetDir, 'pre-commit');
  const display = '.git/hooks/pre-commit';
  if (!fs.existsSync(path.resolve('.git'))) {
    console.log(chalk.yellow(`⚠ Not a git repository (.git/ not found). Skipping pre-commit hook installation.`));
    return;
  }
  if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

  const content = renderPreCommitHook();
  // Checksum is over the BODY only (matches what renderPreCommitHook embeds
  // in the header tag); avoids self-reference.
  const checksum = sha256(PRE_COMMIT_BODY).slice(0, 12);

  if (!fs.existsSync(targetFile)) {
    fs.writeFileSync(targetFile, content);
    fs.chmodSync(targetFile, 0o755);
    console.log(chalk.green(`✓ Installed pre-commit hook: ${display}`));
    console.log(chalk.dim('  Add a .aigisrc.json to your repo root to declare which areas to verify on commit.'));
    console.log(chalk.dim('  Example: { "areas": ["pii-handling", "audit-logging"], "jurisdiction": "eu" }\n'));
    return;
  }

  const existing = fs.readFileSync(targetFile, 'utf8');
  const existingChecksum = (existing.match(/# aigis-hook-checksum: ([a-f0-9]+)/) || [])[1];
  if (existingChecksum === checksum) {
    console.log(chalk.dim(`${display} is up to date.`));
    return;
  }
  if (refresh) {
    fs.writeFileSync(targetFile, content);
    fs.chmodSync(targetFile, 0o755);
    console.log(chalk.green(`✓ Refreshed ${display} (checksum: ${checksum})`));
    return;
  }
  console.log(chalk.yellow(`⚠ ${display} exists with a different checksum.`));
  console.log(chalk.dim(`  Existing: ${existingChecksum || '(no checksum tag — likely not from aigis)'}`));
  console.log(chalk.dim(`  Current:  ${checksum}`));
  console.log(`  Re-run with ${chalk.green('--refresh')} to overwrite (will replace your existing pre-commit hook).`);
}

function renderPreCommitHook() {
  const checksum = sha256(PRE_COMMIT_BODY).slice(0, 12);
  return `#!/usr/bin/env bash
# aigis-hook-checksum: ${checksum}
# Installed by \`aigis init <ide> --hook\`. Re-run with --refresh to update.
# Configure areas to verify by creating a .aigisrc.json in your repo root:
#   { "areas": ["pii-handling", "audit-logging"], "jurisdiction": "eu" }
${PRE_COMMIT_BODY}`;
}

const PRE_COMMIT_BODY = `set -e

if [ ! -f .aigisrc.json ]; then
  echo "[aigis] No .aigisrc.json found. Skipping verify (configure to enable)."
  exit 0
fi

if ! command -v aigis > /dev/null 2>&1; then
  echo "[aigis] aigis CLI not on PATH. Skipping verify (install via 'npm i -g @aigis-ai/cli' or 'pip install aigis-cli')."
  exit 0
fi

AREAS=$(node -e "console.log((JSON.parse(require('fs').readFileSync('.aigisrc.json'))['areas']||[]).join(' '))" 2>/dev/null || echo "")
JUR=$(node -e "console.log(JSON.parse(require('fs').readFileSync('.aigisrc.json'))['jurisdiction']||'')" 2>/dev/null || echo "")

if [ -z "$AREAS" ]; then
  echo "[aigis] .aigisrc.json found but no 'areas' declared. Skipping."
  exit 0
fi

JUR_FLAG=""
if [ -n "$JUR" ]; then
  JUR_FLAG="--jurisdiction $JUR"
fi

FAILED=0
for AREA in $AREAS; do
  if ! aigis verify "$AREA" --auto . $JUR_FLAG > /tmp/aigis-precommit-$AREA.txt 2>&1; then
    echo "[aigis] FAIL or OVERCLAIM in $AREA — blocking commit."
    echo
    tail -40 /tmp/aigis-precommit-$AREA.txt
    echo
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  echo
  echo "[aigis] Commit blocked. Fix the above OR commit with --no-verify to bypass."
  exit 1
fi

echo "[aigis] All declared areas pass. Commit proceeding."
`;

function sha256(s) {
  return require('crypto').createHash('sha256').update(s).digest('hex');
}

function writeOrRefresh(targetFile, content, expectedChecksum, refresh, instruction, ideName, displayName) {
  const display = displayName || targetFile;

  if (!fs.existsSync(targetFile)) {
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`\n✓ Created ${display}\n`));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  const existing = fs.readFileSync(targetFile, 'utf8');
  const match = existing.match(RESOLVER_BLOCK_RE);
  const hasCoreMarker = existing.includes('aigis-core');

  if (!hasCoreMarker && !match) {
    // No previous aigis content. Append.
    fs.appendFileSync(targetFile, '\n\n' + content);
    console.log(chalk.green(`\n✓ Appended aigis core + resolver block to ${display}\n`));
    console.log(chalk.dim('Your existing rules are preserved.\n'));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  if (refresh) {
    // Overwrite the entire file (simple + safe for our format). User opted in.
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`\n✓ Refreshed ${display} (resolver checksum: ${expectedChecksum.slice(0, 12)}...)\n`));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  // Existing block present. Compare checksums.
  if (match && match[1] === expectedChecksum) {
    console.log(chalk.dim(`\n${display} is up to date (resolver checksum matches).\n`));
    return;
  }

  // Mismatch (file exists, but checksum is stale or absent).
  console.log(chalk.yellow(`\n⚠ ${display} already contains an aigis section.`));
  if (match) {
    console.log(chalk.dim(`  Existing block checksum: ${match[1].slice(0, 12)}...`));
    console.log(chalk.dim(`  Current triggers.json:   ${expectedChecksum.slice(0, 12)}...`));
    console.log(chalk.dim('  These differ — your aigis content is out of date or has been edited.'));
  } else {
    console.log(chalk.dim(`  No resolver block detected, but core marker present.`));
  }
  console.log('');
  console.log('Options:');
  console.log(`  ${chalk.green('aigis init ' + ideName + ' --refresh')}    overwrite the file with the current Aigis core + resolver block`);
  console.log(`  manually remove the existing aigis section, then re-run ${chalk.green('aigis init ' + ideName)}`);
  console.log('');
  process.exit(1);
}

module.exports = {
  init,
  buildFullContent,
  renderResolverBlock,
  installGithubAction,
  installPreCommitHook,
  renderGithubActionWorkflow,
  renderPreCommitHook,
};
