const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const { getCore } = require('./fetch');
const { loadTriggers, TRIGGERS_PATH } = require('./keywords');
const { computeFileChecksum } = require('./checksum');

const HEADER = `# Aigis core skill — installed by \`aigis init\`
# Re-run \`aigis init <ide>\` to refresh this file when Aigis updates.
# Area + workflow skills load on demand via the aigis CLI; they are NOT in this file.

`;

const RESOLVER_BLOCK_START = (checksum) =>
  `# --- AIGIS RESOLVER BLOCK START (checksum: ${checksum}) ---`;
const RESOLVER_BLOCK_END = `# --- AIGIS RESOLVER BLOCK END ---`;
const RESOLVER_BLOCK_RE = /# --- AIGIS RESOLVER BLOCK START \(checksum: ([a-f0-9]+)\) ---[\s\S]*?# --- AIGIS RESOLVER BLOCK END ---/m;

const IDE_DESTINATIONS = {
  cursor:        { file: '.cursorrules',                  description: 'Cursor rules file',          instruction: 'Cursor will read these instructions on every interaction in this project.' },
  windsurf:      { file: '.windsurfrules',                description: 'Windsurf rules file',         instruction: 'Windsurf will read these instructions on every interaction in this project.' },
  copilot:       { file: '.github/copilot-instructions.md', description: 'GitHub Copilot instructions', instruction: 'Copilot will read these instructions for this repository.' },
  'claude-code': { file: null,                            description: 'Claude Code skill file',      instruction: 'Claude Code will read this skill file. Restart Claude Code for it to take effect.' },
};

/**
 * Render the resolver block as a human-readable markdown table the agent can
 * consume directly. Format is deterministic: alphabetical row order within
 * each tier, fixed column widths, no trailing whitespace.
 */
function renderResolverBlock(checksum) {
  const triggers = loadTriggers();

  const lines = [];
  lines.push(RESOLVER_BLOCK_START(checksum));
  lines.push(`# Generated by \`aigis init\` from content/resolvers/triggers.json (version ${triggers.version}).`);
  lines.push(`# Do not edit manually. Run \`aigis init <ide> --refresh\` to regenerate after Aigis updates.`);
  lines.push(`#`);
  lines.push(`# When the user describes their project in natural language, scan the description`);
  lines.push(`# for the phrases below.`);
  lines.push(`#`);
  lines.push(`# HIGH-CONFIDENCE: apply the listed traits directly.`);
  lines.push(`# LOW-CONFIDENCE:  ask the user the listed clarifying question; apply the trait`);
  lines.push(`#                  only if they confirm "yes". Default to "no" if the user is`);
  lines.push(`#                  unsure. Record "unsure" answers distinctly from "no" so future`);
  lines.push(`#                  iterations can ask again.`);
  lines.push('');
  lines.push('## High-confidence triggers (auto-apply)');
  lines.push('');

  const hiKeys = Object.keys(triggers.high_confidence);
  const phraseW = Math.max(6, ...hiKeys.map((k) => k.length));
  const traitsW = Math.max(6, ...hiKeys.map((k) => triggers.high_confidence[k].traits.join(', ').length));
  lines.push(`| ${'Phrase'.padEnd(phraseW)} | ${'Traits'.padEnd(traitsW)} |`);
  lines.push(`|${'-'.repeat(phraseW + 2)}|${'-'.repeat(traitsW + 2)}|`);
  for (const k of hiKeys) {
    lines.push(`| ${k.padEnd(phraseW)} | ${triggers.high_confidence[k].traits.join(', ').padEnd(traitsW)} |`);
  }

  lines.push('');
  lines.push('## Low-confidence triggers (confirm with user before applying)');
  lines.push('');

  const loKeys = Object.keys(triggers.low_confidence);
  const lpW = Math.max(6, ...loKeys.map((k) => k.length));
  const ltW = Math.max(6, ...loKeys.map((k) => triggers.low_confidence[k].traits.join(', ').length));
  // Question column kept compact — the full prompt is long; we render the trailing
  // question only (sentence between "You mentioned X." and the "(yes / no / unsure)" suffix).
  function shortQuestion(prompt) {
    const m = prompt.match(/^You mentioned [^.]+\.\s*(.+?)\s*\(yes \/ no \/ unsure\)\s*$/);
    return m ? m[1] : prompt;
  }
  const askW = Math.max(6, ...loKeys.map((k) => shortQuestion(triggers.low_confidence[k].confirmation_prompt).length));
  lines.push(`| ${'Phrase'.padEnd(lpW)} | ${'Traits'.padEnd(ltW)} | ${'Ask the user'.padEnd(askW)} |`);
  lines.push(`|${'-'.repeat(lpW + 2)}|${'-'.repeat(ltW + 2)}|${'-'.repeat(askW + 2)}|`);
  for (const k of loKeys) {
    const e = triggers.low_confidence[k];
    lines.push(`| ${k.padEnd(lpW)} | ${e.traits.join(', ').padEnd(ltW)} | ${shortQuestion(e.confirmation_prompt).padEnd(askW)} |`);
  }

  lines.push('');
  lines.push(RESOLVER_BLOCK_END);
  return lines.join('\n');
}

function buildFullContent() {
  const checksum = computeFileChecksum(TRIGGERS_PATH);
  const block = renderResolverBlock(checksum);
  return { content: HEADER + getCore() + '\n\n' + block + '\n', checksum };
}

function init(ide, opts = {}) {
  const ideLower = ide.toLowerCase();
  const dest = IDE_DESTINATIONS[ideLower];
  if (!dest) {
    console.error(chalk.red(`Unknown IDE: ${ide}`));
    console.log(chalk.dim('Available: cursor, claude-code, windsurf, copilot\n'));
    process.exit(1);
  }

  const { content, checksum } = buildFullContent();

  // Claude Code: dedicated skill dir
  if (ideLower === 'claude-code') {
    const skillDir = path.join(require('os').homedir(), '.claude', 'skills', 'aigis');
    const skillFile = path.join(skillDir, 'SKILL.md');
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    writeOrRefresh(skillFile, content, checksum, opts.refresh, dest.instruction, ideLower);
    return;
  }

  // Other IDEs
  const targetFile = path.resolve(dest.file);
  const targetDir = path.dirname(targetFile);
  if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
  writeOrRefresh(targetFile, content, checksum, opts.refresh, dest.instruction, ideLower, dest.file);
}

function writeOrRefresh(targetFile, content, expectedChecksum, refresh, instruction, ideName, displayName) {
  const display = displayName || targetFile;

  if (!fs.existsSync(targetFile)) {
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`\n✓ Created ${display}\n`));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  const existing = fs.readFileSync(targetFile, 'utf8');
  const match = existing.match(RESOLVER_BLOCK_RE);
  const hasCoreMarker = existing.includes('aigis-core');

  if (!hasCoreMarker && !match) {
    // No previous aigis content. Append.
    fs.appendFileSync(targetFile, '\n\n' + content);
    console.log(chalk.green(`\n✓ Appended aigis core + resolver block to ${display}\n`));
    console.log(chalk.dim('Your existing rules are preserved.\n'));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  if (refresh) {
    // Overwrite the entire file (simple + safe for our format). User opted in.
    fs.writeFileSync(targetFile, content);
    console.log(chalk.green(`\n✓ Refreshed ${display} (resolver checksum: ${expectedChecksum.slice(0, 12)}...)\n`));
    console.log(chalk.dim(instruction + '\n'));
    return;
  }

  // Existing block present. Compare checksums.
  if (match && match[1] === expectedChecksum) {
    console.log(chalk.dim(`\n${display} is up to date (resolver checksum matches).\n`));
    return;
  }

  // Mismatch (file exists, but checksum is stale or absent).
  console.log(chalk.yellow(`\n⚠ ${display} already contains an aigis section.`));
  if (match) {
    console.log(chalk.dim(`  Existing block checksum: ${match[1].slice(0, 12)}...`));
    console.log(chalk.dim(`  Current triggers.json:   ${expectedChecksum.slice(0, 12)}...`));
    console.log(chalk.dim('  These differ — your aigis content is out of date or has been edited.'));
  } else {
    console.log(chalk.dim(`  No resolver block detected, but core marker present.`));
  }
  console.log('');
  console.log('Options:');
  console.log(`  ${chalk.green('aigis init ' + ideName + ' --refresh')}    overwrite the file with the current Aigis core + resolver block`);
  console.log(`  manually remove the existing aigis section, then re-run ${chalk.green('aigis init ' + ideName)}`);
  console.log('');
  process.exit(1);
}

module.exports = { init, buildFullContent, renderResolverBlock };
